### ISSUE TITLE
Can this be run in web jobs?

### ISSUE THREAD

**Issue by jlkalberer** [garvincasimir/Elasticsearch-Azure-PAAS#21]
I'm pretty unfamiliar with how this actually works.  I have a really low traffic site but I need ES and was hoping I could just add it via a web job.

**Comment by garvincasimir** [comment]
It might be possible in a continuous web job if are using a single instance in your app service plan.

**Comment by jlkalberer** [comment]
Ok, thanks.  I tried getting this set up but I was missing some Azure SDK dlls.  I'll post back here if I can get this working.

**Comment by garvincasimir** [comment]
I updated the code recently but have not updated the nuget package. how are you testing it?

**Comment by jlkalberer** [comment]
Nuget.  I'll compile locally and try that tonight.

**Comment by garvincasimir** [comment]
The nuget version works with ES v1.4

**Comment by jlkalberer** [comment]
Alright, I pulled down latest but I'm having issues compiling. Looks like Worker.Common won't build because NEST was updated and you're still using an old version there?

**Comment by jlkalberer** [comment]
OK, I'm guessing that the webjob doesn't have appropriate permissions or something. With the nuget package I fail like this:
```
[10/12/2016 22:37:11 > c6c8fb: ERR ] Unhandled Exception: System.InvalidOperationException: role discovery data is unavailable
[10/12/2016 22:37:11 > c6c8fb: ERR ]    at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.get_CurrentRoleInstance()
[10/12/2016 22:37:11 > c6c8fb: ERR ]    at ElasticsearchWorker.Core.ElasticsearchServiceSettings.FromStorage(CloudStorageAccount account)
[10/12/2016 22:37:11 > c6c8fb: ERR ]    at Keg.ElasticSearch.Program.Main()
```

**Comment by jlkalberer** [comment]
Ok.. I see that I would need to set up the config myself instead of doing it with the helper.  I'm thinking I'll just bite the bullet and create a cloud service.  It will be better for deployments if I move my site under that anyways.

**Comment by garvincasimir** [comment]
Sorry I should have provided more detail in my response. This will not work in a Webjob without customization. And even with customization you will probably only get one instance.

1. You need to implement your own  IElasticsearchServiceSettings.cs. (AppSettingsESserviceSettings.cs perhaps?)
2. I am assuming the JVM is already installed on these instances but we probably don't have access to the registry to discover the path (needs verification).
3. I don't know that you can mount azure file storage so you might be stuck with local storage (needs verification)
4. The discovery plugin and service is specifically designed to work with Web and Worker Roles so you would need to remove them. I don't know of any available api that would allow discovery for multiple instances in App Services.

**Comment by jlkalberer** [comment]
Yeah, makes sense.  I gave up on it because if I ever needed to scale I'd have to do this all over again :)

Anyways, I'm running into the issue now about setting `JAVA_PATH` in the cloud emulator.  Any ideas what that's about?

**Comment by garvincasimir** [comment]
You need to upload the java installer to your storage account and put the url in the appropriate setting

**Comment by jlkalberer** [comment]
I used a web url and that is downloading and starting the installer.  The
actual error message is complaining about setting `JAVA_HOME`.

**Comment by garvincasimir** [comment]
What is the actual error message? Are you running visual studio as an administrator?

**Comment by jlkalberer** [comment]
Ahhh... thank you so much. I haven't worked with cloud services in years
and forgot about the "run as administrator" issues.

**Comment by garvincasimir** [comment]
No problem.

**Comment by garvincasimir** [comment]
How did it go?

**Comment by jlkalberer** [comment]
Yeah, that worked.  I'm still working on it with the emulator for now (trying to get a good analyzer working) but other than that there are no problems.  It would be awesome if you pushed the latest package to nuget :)

**Comment by garvincasimir** [comment]
I could not push the package until I confirmed everything was working. I think it is safe to tag the release now. Thanks for testing it.

**Comment by jlkalberer** [comment]
Whoah... Wait a minute. I used the old version on nuget.

I couldn't test because this repo wouldn't build on my machine.. but that
may have been an SDK issue.

**Comment by garvincasimir** [comment]
Oh I guess I need to do those tests then.

**Comment by jlkalberer** [comment]
Yeah.. I just pulled again and couldn't get it to build.  I don't know if there is an issue with building the nuget packages or what but the main dll won't build.

**Comment by garvincasimir** [comment]
If you updated the packages before building, the Elasticsearch .net client has breaking chances.

**Comment by garvincasimir** [comment]
Nuget package updated to Elasticsearch v5
