### ISSUE TITLE
Elasticsearch binding 'problem' when deployed to Azure

### ISSUE THREAD

**Issue by sh3rndon** [garvincasimir/Elasticsearch-Azure-PAAS#22]
This is not really an issue with the project, but something I learned that might save others time. Elasticsearch 2.4.1 (don't know about other versions) will bind to the loopback address by default if you don't specify an address in the configuration file. This is OK when running in the Emulator, but can be problematic when you deploy to Azure because even if you define the correct endpoint in the role settings, you won't be able to connect to Elasticsearch. Binding to the address '0' will allow the Elasticsearch instance to accept requests on the endpoint you have defined.

**Comment by garvincasimir** [comment]
Thanks for the nice tip @sh3rndon :)
