### ISSUE TITLE
[feature request] file based discovery

### ISSUE THREAD

**Issue by hanabi1224** [garvincasimir/Elasticsearch-Azure-PAAS#23]
With file based discovery, i think it will make it easier to upgrade to latest ES by getting rid of azure-runtime java plugin
https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-file.html

**Comment by garvincasimir** [comment]
Getting rid of the java runtime plugin in favor of this would definitely simplify the upgrade process for me (Every version has breaking changes). However, I am not sure how it would help someone consuming this library. For example, you would be required to include discovery-file-5.3.0.zip in either your visual studio project or your **Installs** storage container for ES 5.3.0. At least the java plugin is included  in the Nuget package.

**Comment by hanabi1224** [comment]
@garvincasimir I think you can have a config field of all required plugin names, and install plugins in ElasticSearchManager with elasticsearch-plugin.bat

**Comment by garvincasimir** [comment]
I can add the option if you like. To be honest, I purposely avoided relying on the built in plugin installer because i don't believe a running system should rely on Github and similar sites for packages once deployed.

**Comment by garvincasimir** [comment]
Decided to remove the java plugin and use Zen Discovery. Discovery-file not required. Upgrades should be a lot easier from this point.

**Comment by hanabi1224** [comment]
@garvincasimir Does it work when you scale up the number of instances?

**Comment by garvincasimir** [comment]
Yes it does work when you scale up the number of instances. Please let me know if you encounter any problems. 

I also added the option for installing plugins with a pipe separated config value. Note that it is significantly slower than the 2 other available options for installing plugins.

**Comment by hanabi1224** [comment]
@garvincasimir  awesome, thanks!
